services:
  database:
    image: postgres:17
    container_name: directus-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus -d directus"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  directus:
    image: directus/directus:11.5.0
    container_name: directus
    restart: always
    ports:
      - "8055:${DIRECTUS_PORT}"
    volumes:
      - directus_database:/directus/database
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
    environment:
      SECRET: "${DIRECTUS_SECRET}"
      ADMIN_EMAIL: "${DIRECTUS_EMAIL}"
      ADMIN_PASSWORD: "${DIRECTUS_PASSWORD}"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      WEBSOCKETS_ENABLED: "true"
      ACCESS_TOKEN_TTL: "3600"
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:
  directus_database:
  directus_uploads:
  directus_extensions: